// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jasperreports.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.core.conf.RuntimeVersion;
import com.mendix.core.objectmanagement.member.MendixBoolean;

/**
 * Get sample JasperReports jasper file from userlib jar file.
 */
public class getSampleForm extends CustomJavaAction<IMendixObject>
{
	private java.lang.String File;

	public getSampleForm(IContext context, java.lang.String File)
	{
		super(context);
		this.File = File;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		InputStream is = null;
		IMendixObject obj = Core.instantiate(getContext(), "JasperReports.JasperForms");
		try {
			is = getClass().getResourceAsStream(File);
			Core.storeFileDocumentContent(getContext(), obj, is);
		} catch (Exception e) {
			Core.getLogger("JasperReportsUtil").error("Couldn't read File");
			Core.getLogger("JasperReportsUtil").error(e.toString());
		} finally {
			if (is != null) {
				is.close();
			}
	}
		return obj;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "getSampleForm";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
